### PR TITLE
Add --live option

### PR DESCRIPTION
**Pull request by deldesir**
## Description

This pull request introduces a new --live flag to enable the download of live videos. This flag adjusts the match filters to include live streams, which were previously excluded by default.

## Motivation and Context

The primary motivation for this change is to allow users to download live videos directly, a feature that was not supported due to default match filters excluding live content.

Some context: https://github.com/iiab/calibre-web/issues/188

## How has this been tested?

The changes were tested by:
- Implementing the --live flag and ensuring it correctly modifies the match filters.
- Running the updated script to download live videos from various sources to confirm the flag's effectiveness.
- Verifying that non-live videos are still downloadable without the --live flag.
- Ensuring no regression in existing functionalities.

Tested on Ubuntu 24.04

## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by holta** [comment]
@deldesir what happens when someone accidentally tries to download a *"genuinely live"* YouTube video — that's actually being recorded live at that moment — e.g. a video from a webcam that might never end?

(As distinct from *"formerly live"* YouTube videos, which people are currently being blocked from downloading!)

**Comment by holta** [comment]
> > It will be downloaded from the current time.
> 
> Are you saying the download will never end?

I had (wrongly) assumed YouTube could record endless videos, e.g. from a wilderness scientist's webcam.

In fact, YouTube video recordings seem to currently be limited to **"12 hours long, or 128 GB"** according to https://www.quora.com/Whats-the-maximum-video-length-on-YouTube-or-is-it-dependent-on-video-size

- So, to clarify my question: let's say we're 1-hour into a 12-hour-long "actually live" tennis match, when a teacher/parent suddenly then asks Calibre-Web to start downloading the tennis match video — will that single video download take 11 hours to complete?

- Regardless, can we use the `--live-from-start` flag by default?  (Even if it downloads the 1st hour of the tennis match very rapidly, and then drags on very slowly while downloading the final 11 hours ???)

**Comment by holta** [comment]
Just FYI I'm trying to understand the true high-level objectives here.

So @deldesir is helping to explain some of those underlying motivations (and needs) in this conversation here:

- https://github.com/iiab/calibre-web/issues/188#issuecomment-2188818111

**Comment by chapmanjacobd** [comment]
yeah this looks good. can you add `@skip("network")` to the test?

**Review by chapmanjacobd — COMMENTED** [review]
skip isn't imported. check the other files for an example

**Comment by deldesir** [comment]
Done.

**Comment by chapmanjacobd** [comment]
https://github.com/chapmanjacobd/library/commit/a49e1a01cc1f765728bf43143f469ff15c5ab1b9

https://github.com/chapmanjacobd/library/actions/runs/9687571930

**Pull request merged**
